version: 0.5

index_id: foo

doc_mapping:
  field_mappings:
    - name: url
      fast: true
      type: text
      tokenizer: raw
      record: position
    - name: title
      type: text
      tokenizer: default
      record: position
      fieldnorms: true
    - name: body
      type: text
      tokenizer: default
      record: position
      fieldnorms: true

search_settings:
  default_search_fields: [title, body]

indexing_settings:
  commit_timeout_secs: 1
